
local macro
do
   local instance_members = {}
   macro = make_class({
      constructor = function(self, name, node)
         self.name = name
         self.node = node
         
         self.data_node  = nil
         self.parameters = {}
         node:for_each_child_element(function(node)
            if node.node_name == "data" then
               self.data_node = node
            elseif node.node_name == "parameter" then
               local name = node.attributes["name"]
               local dv   = node.attributes["default-value"]
               self.parameters[name] = {
                  name    = name,
                  default = dv,
               }
            else
               error("unexpected node: " .. node.node_name)
            end
         end)
         if not self.data_node then
            error("macro missing <data/> node")
         end
      end,
      instance_members = instance_members
   })
   do -- instance members
      function instance_members:substitution_must_be_permanent(invocation)
         --
         -- A macro's substitution must be permanent if the macro generates 
         -- any forms that are identified solely by form ID (i.e. not given 
         -- a unique editor ID).
         --
         -- If the following nodes are generated by a macro, then substitution
         -- must be permanent:
         --
         --    actor
         --    quest
         --    quest :is(top-g, g, line, shared-info)
         --
         -- Therefore this function's result depends on the invocation site.
         --
         local is_in_quest = false
         do
            local node = invocation.parent
            while node do
               if node.node_name == "quest" then
                  is_in_quest = true
                  break
               end
               node = node.parent
            end
         end
         
         local result = false
         local walk
         if is_in_quest then
            walk = function(node)
               if node.node_name == "top-g"
               or node.node_name == "g"
               or node.node_name == "line"
               or node.node_name == "shared-info"
               then
                  result = true
                  return false
               end
               if xml.element.is(node) then
                  node:for_each_child_element(walk)
               end
            end
         else
            walk = function(node)
               if node.node_name == "actor"
               or node.node_name == "quest"
               then
                  result = true
                  return false
               end
               if xml.element.is(node) then
                  node:for_each_child_element(walk)
               end
            end
         end
         
         walk(self.node)
         return result
      end
      function instance_members:substitute(invocation)
         local is_permanent = self:substitution_must_be_permanent(invocation)
         
         if is_permanent then
            do
               local builder = string_builder()
               invocation:serialize(builder)
               xml.comment(builder:to_string()):place_before(invocation)
            end
            xml.comment(" macro substitution end "):place_after(invocation)
         end
         
         local param_values = {}
         invocation:for_each_child_element(function(node)
            if node.node_name == "parameter" then
               local n = node.attributes["name"]
               local v = node.attributes["value"]
               if n and v then
                  param_values[n] = v
               end
            end
         end)
         
         local subtree = self.data_node:clone(true)
         do -- perform string substitutions
            local function subst(text)
               local from = 1
               repeat
                  local i = text:find("%", from, true)
                  if not i then
                     break
                  end
                  local j = text:find("%", i + 1, true)
                  if not j then
                     break
                  end
                  local name = text:sub(i + 1, j - 1)
                  local val  = param_values[name]
                  if not val then
                     from = j + 1
                     goto continue
                  end
                  text = text:sub(1, i - 1) .. val .. text:sub(j + 1)
                  from = i
                  ::continue::
               until true
               return text
            end
            
            for k, v in pairs(self.parameters) do
               if not param_values[k] then
                  local d = v.default
                  if d then
                     d = subst(d)
                  end
                  param_values[k] = d
               end
            end
         
            local function walk(node)
               if xml.comment.is(node) or xml.text.is(node) then
                  node.data = subst(node.data)
               end
               if xml.element.is(node) then
                  for k, v in pairs(node.attributes) do
                     node.attributes[k] = subst(v)
                  end
                  node:for_each_child(walk)
               end
            end
            walk(subtree)
            if not is_permanent then
               for i = 1, #subtree.children do
                  local node = subtree.children[i]
                  node.__is_macro_substitution = true
                  if i == 1 then
                     node.__source_invocation = invocation
                  end
               end
            end
            invocation:replace_with(table.unpack(subtree.children))
         end
      end
   end
end

macros = {}

function macros.transform(root)
   local macro_definitions = {} -- vector<macro>
   local macros_in_scope   = {} -- vector<macro>
   
   local function walk(node)
      if node.node_name == "macro" then
         local name = node.attributes["name"]
         if not name or name == "" then
            error("nameless macro")
         end
         local list = macro_definitions[name]
         if not list then
            list = {}
            macro_definitions[name] = list
         end
         local item = macro(name, node)
         list[#list + 1] = item
         macros_in_scope[#macros_in_scope + 1] = item
      elseif node.node_name == "invoke" then
         local name = node.attributes["name"]
         if not name or name == "" then
            error("nameless macro invocation")
         end
         local list = macro_definitions[name]
         if not list then
            error("macro not found: " .. name)
         end
         local dfn = list[#list]
         if not dfn then
            error("macro not found: " .. name)
         end
         dfn:substitute(node)
      else
         local prior = #macros_in_scope
         node:for_each_child_element(walk)
         local after = #macros_in_scope
         if after > prior then
            --
            -- These macros must necessarily have gone out of scope.
            --
            for i = prior + 1, after do
               local macro = macros_in_scope[i]
               local name  = macro.name
               local list  = macro_definitions[name]
               for j = 1, #list do
                  if list[j] == macro then
                     table.remove(list, j)
                     break
                  end
               end
            end
         end
      end
   end
   
   walk(root)
end
function macros.revert(root)
   local function walk(node)
      if xml.element.is(node) then
         local retain = {}
         local change = false
         for i = 1, #node.children do
            local child = node.children[i]
            if child.__is_macro_substitution then
               change = true
               if child.__source_invocation then
                  retain[#retain + 1] = child.__source_invocation
               end
            else
               retain[#retain + 1] = child
            end
         end
         if change then
            node:replace_children(table.unpack(retain))
         end
         for i = 1, #node.children do
            walk(node.children[i])
         end
      end
   end
   walk(root)
end