
--
-- NOTE: nested macro invocations not supported
--

local macro
do
   local instance_members = {}
   macro = make_class({
      constructor = function(self, name, node)
         self.name = name
         self.node = node
         
         self.data_node  = nil
         self.parameters = {}
         node:for_each_child_element(function(node)
            if node.node_name == "data" then
               self.data_node = node
            elseif node.node_name == "parameter" then
               local name = node.attributes["name"]
               local dv   = node.attributes["default-value"]
               self.parameters[name] = {
                  name    = name,
                  default = dv,
               }
            else
               utils.fail_load_on_unexpected_element(node)
            end
         end)
         if not self.data_node then
            utils.fail_load("macro missing <data/> node", node)
         end
      end,
      instance_members = instance_members
   })
   do -- instance members
      function instance_members:substitution_must_be_permanent(invocation)
         --
         -- A macro's substitution must be permanent if the macro generates 
         -- any forms that are identified solely by form ID (i.e. not given 
         -- a unique editor ID).
         --
         -- If the following nodes are generated by a macro, then substitution
         -- must be permanent:
         --
         --    actor
         --    quest
         --    quest :is(top-g, g, line, shared-info)
         --
         -- Therefore this function's result depends on the invocation site.
         --
         local substitutes_in_permanent_elements = false
         invocation:for_each_child_element(function(node)
            if node.node_name == "parameter" and not node.attributes["value"] then
               node:for_each_child_element(function(child)
                  if not xml.element.is(child) then
                     return
                  end
                  if child.node_name == "top-g"
                  or child.node_name == "g"
                  or child.node_name == "line"
                  or child.node_name == "shared-info" then
                     substitutes_in_permanent_elements = true
                     return false
                  end
               end)
            end
         end)
         if substitutes_in_permanent_elements then
            return true
         end
         
         local is_in_quest = false
         do
            local node = invocation.parent
            while node do
               if node.node_name == "quest" then
                  is_in_quest = true
                  break
               end
               node = node.parent
            end
         end
         
         local result = false
         local walk
         if is_in_quest then
            walk = function(node)
               if node.node_name == "top-g"
               or node.node_name == "g"
               or node.node_name == "line"
               or node.node_name == "shared-info"
               then
                  result = true
                  return false
               end
               if xml.element.is(node) then
                  node:for_each_child_element(walk)
               end
            end
         else
            walk = function(node)
               if node.node_name == "actor"
               or node.node_name == "quest"
               then
                  result = true
                  return false
               end
               if xml.element.is(node) then
                  node:for_each_child_element(walk)
               end
            end
         end
         
         walk(self.node)
         return result
      end
      function instance_members:substitute(invocation)
         local is_permanent = self:substitution_must_be_permanent(invocation)
         
         if is_permanent then
            do
               local builder = string_builder()
               invocation:serialize(builder)
               xml.comment(builder:to_string()):place_before(invocation)
            end
            xml.comment(" macro substitution end "):place_after(invocation)
         end
         
         local param_values   = {}
         local param_subtrees = {}
         invocation:for_each_child_element(function(node)
            if node.node_name == "parameter" then
               local n = node.attributes["name"]
               local v = node.attributes["value"]
               if not n then
                  return
               end
               if v then
                  param_values[n] = v
               else
                  param_subtrees[n] = node.children
               end
            end
         end)
         
         local subtree = self.data_node:clone(true)
         do -- perform string substitutions
            local function subst(text)
               local from = 1
               repeat
                  local i = text:find("%", from, true)
                  if not i then
                     break
                  end
                  local j = text:find("%", i + 1, true)
                  if not j then
                     break
                  end
                  local name = text:sub(i + 1, j - 1)
                  local val  = param_values[name]
                  if not val then
                     if param_subtrees[name] then
                        error("Subtree substitutions are not permitted here.");
                     end
                     from = j + 1
                     goto continue
                  end
                  text = text:sub(1, i - 1) .. val .. text:sub(j + 1)
                  from = i
                  ::continue::
               until true
               return text
            end
            
            local function subst_text_node(node)
               local parts = {}
               local text = node.data
               local from  = 1
               repeat
                  local i = text:find("%", from, true)
                  if not i then
                     break
                  end
                  local j = text:find("%", i + 1, true)
                  if not j then
                     break
                  end
                  local name = text:sub(i + 1, j - 1)
                  local val  = param_values[name]
                  if not val then
                     val = param_subtrees[name]
                     if not val then
                        goto continue
                     end
                  end
                  parts[#parts + 1] = text:sub(from, i - 1)
                  parts[#parts + 1] = val
                  ::continue::
                  from = j + 1
               until true
               if from < #text then
                  parts[#parts + 1] = text:sub(from)
               end
               if #parts == 1 and parts[1] == text then
                  return
               end
               
               local nodes = {}
               for _, part in ipairs(parts) do
                  if type(part) == "string" then
                     nodes[#nodes + 1] = xml.text(part)
                  else
                     for _, src in ipairs(part) do
                        nodes[#nodes + 1] = src:clone(true)
                     end
                  end
               end
               node:replace_with(table.unpack(nodes))
            end
            
            for k, v in pairs(self.parameters) do
               if not param_values[k] and not param_subtrees[k] then
                  local d = v.default
                  if d then
                     d = subst(d) -- subst because one parameter can be defaulted to another
                  else
                     utils.fail_load("macro parameter `" .. k .. "` was not specified", invocation)
                  end
                  param_values[k] = d
               end
            end
         
            local function walk(node)
               if xml.comment.is(node) then
                  node.data = subst(node.data)
               end
               if xml.text.is(node) then
                  node = subst_text_node(node)
               end
               if xml.element.is(node) then
                  for k, v in pairs(node.attributes) do
                     node.attributes[k] = subst(v)
                  end
                  node:for_each_child(walk)
               end
            end
            walk(subtree)
            if not is_permanent then
               for i = 1, #subtree.children do
                  local node = subtree.children[i]
                  node.__is_macro_substitution = true
                  if i == 1 then
                     node.__source_invocation = invocation
                  end
               end
            end
            invocation:replace_with(table.unpack(subtree.children))
         end
      end
   end
end

macros = {}

function macros.gather_global_macros(root, dst_set)
   root:for_each_child_element(function(node)
      if node.node_name ~= "global-macros" then
         return
      end
      node:for_each_child_element(function(node)
         if node.node_name ~= "macro" then
            return
         end
         local name = node.attributes["name"]
         if not name or name == "" then
            utils.fail_load("nameless macro", node)
         end
         if dst_set[name] then
            utils.fail_load("redefinition of global macro `" .. name .. "`", node)
         end
         local item = macro(name, node)
         dst_set[name] = item
      end)
   end)
end

function macros.transform(root, global_macros)
   local macro_definitions = {} -- vector<macro>
   local macros_in_scope   = {} -- vector<macro>
   
   local function walk(node)
      if node.node_name == "macro" then
         local name = node.attributes["name"]
         if not name or name == "" then
            utils.fail_load("nameless macro", node)
         end
         local list = macro_definitions[name]
         if not list then
            list = {}
            macro_definitions[name] = list
         end
         local item = macro(name, node)
         list[#list + 1] = item
         macros_in_scope[#macros_in_scope + 1] = item
      elseif node.node_name == "invoke" then
         local name = node.attributes["name"]
         if not name or name == "" then
            utils.fail_load("nameless macro invocation", node)
         end
         local dfn
         do
            local list = macro_definitions[name]
            if list then
               dfn = list[#list]
            else
               dfn = (global_macros or {})[name]
            end
         end
         if not dfn then
            utils.fail_load("macro not found: " .. name, node)
         end
         dfn:substitute(node)
      else
         local prior = #macros_in_scope
         do
            local children = { table.unpack(node.children) }
            for i = 1, #children do
               local child = children[i]
               if xml.element.is(child) then
                  walk(child)
               end
            end
         end
         local after = #macros_in_scope
         if after > prior then
            --
            -- These macros must necessarily have gone out of scope.
            --
            for i = prior + 1, after do
               local macro = macros_in_scope[i]
               local name  = macro.name
               local list  = macro_definitions[name]
               for j = 1, #list do
                  if list[j] == macro then
                     table.remove(list, j)
                     break
                  end
               end
            end
         end
      end
   end
   
   walk(root)
end
function macros.revert(root)
   local function walk(node)
      if xml.element.is(node) then
         local retain = {}
         local change = false
         for i = 1, #node.children do
            local child = node.children[i]
            if child.__is_macro_substitution then
               change = true
               if child.__source_invocation then
                  retain[#retain + 1] = child.__source_invocation
               end
            else
               retain[#retain + 1] = child
            end
         end
         if change then
            node:replace_children(table.unpack(retain))
         end
         for i = 1, #node.children do
            walk(node.children[i])
         end
      end
   end
   walk(root)
end